# Generated by Django 4.2 on 2023-08-31 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_recipe_recipe_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_by',
        ),
    ]
