# Generated by Django 4.2 on 2023-09-02 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_recipe_recipe_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_by',
        ),
    ]
